# -*- conf -*-
# Mortal Kombat

[main]
initial-color-theme=dark

[colors-dark]
alpha=0.90
alpha-mode=all
blur=yes

background=000000
foreground=c2cadd

regular0=272e50
regular1=ff8c00
regular2=394f95
regular3=9d4edd
regular4=00d9ff
regular5=575864
regular6=6b96b4
regular7=c2cadd

bright0=33475f
bright1=ff8c00
bright2=6b96b4
bright3=9d4edd
bright4=00d9ff
bright5=986f99
bright6=646891
bright7=ffffff

selection-foreground=c2cadd
selection-background=272e50
urls=9d4edd

[colors-light]
alpha=0.88
alpha-mode=all
blur=yes

background=eff1f5
foreground=4c4f69

regular0=acb0be
regular1=d20f39
regular2=40a02b
regular3=df8e1d
regular4=1e66f5
regular5=ea76cb
regular6=179299
regular7=6c6f85

bright0=9ca0b0
bright1=d20f39
bright2=40a02b
bright3=df8e1d
bright4=1e66f5
bright5=ea76cb
bright6=179299
bright7=7c7f93

selection-foreground=4c4f69
selection-background=acb0be
urls=1e66f5
