# Mortal Kombat (Mortalkombat.png)
# class                 border    background text      indicator child_border
client.focused          #9d4edd   #272e50    #c2cadd   #9d4edd   #9d4edd
client.focused_inactive #646891   #272e50    #979ba2   #646891   #646891
client.unfocused        #33475f   #000000    #575864   #33475f   #33475f
client.urgent           #ff8c00   #272e50    #000000   #ff8c00   #ff8c00
client.placeholder      #272e50   #000000    #4f393c   #272e50   #272e50

default_border pixel 2
default_floating_border pixel 2
