# -*- conf -*-
# The Mandalorian

[main]
initial-color-theme=dark

[colors-dark]
alpha=0.88
alpha-mode=all
blur=yes

background=0b0707
foreground=fcf9f7

regular0=682f31
regular1=ea827d
regular2=b24c4e
regular3=f9cbb6
regular4=f29d93
regular5=977e80
regular6=8f3a3e
regular7=fcf9f7

bright0=682f31
bright1=f29d93
bright2=f9cbb6
bright3=fcf9f7
bright4=ea827d
bright5=d46262
bright6=977e80
bright7=ffffff

selection-foreground=fcf9f7
selection-background=682f31
urls=ea827d

[colors-light]
alpha=0.88
alpha-mode=all
blur=yes

background=eff1f5
foreground=4c4f69

regular0=acb0be
regular1=d20f39
regular2=40a02b
regular3=df8e1d
regular4=1e66f5
regular5=ea76cb
regular6=179299
regular7=6c6f85

bright0=9ca0b0
bright1=d20f39
bright2=40a02b
bright3=df8e1d
bright4=1e66f5
bright5=ea76cb
bright6=179299
bright7=7c7f93

selection-foreground=4c4f69
selection-background=acb0be
urls=1e66f5
