# The Mandalorian (mandalorian.jpg)
# class                 border    background text      indicator child_border
client.focused          #ea827d   #682f31    #fcf9f7   #ea827d   #ea827d
client.focused_inactive #977e80   #682f31    #f9cbb6   #977e80   #977e80
client.unfocused        #8f3a3e   #0b0707    #b24c4e   #8f3a3e   #8f3a3e
client.urgent           #fcf9f7   #682f31    #0b0707   #fcf9f7   #fcf9f7
client.placeholder      #682f31   #0b0707    #977e80   #682f31   #682f31

default_border pixel 2
default_floating_border pixel 2
