# -*- conf -*-
# Retro Eighties

[main]
initial-color-theme=dark

[colors-dark]
alpha=0.88
alpha-mode=all
blur=yes

background=1f1b24
foreground=bca9bd

regular0=514249
regular1=ff4da6
regular2=39c5cf
regular3=da9e50
regular4=8b75c2
regular5=5d515d
regular6=394ca3
regular7=bca9bd

bright0=242c56
bright1=ff69b4
bright2=39c5cf
bright3=da9e50
bright4=ff4da6
bright5=8b75c2
bright6=514249
bright7=ffffff

selection-foreground=bca9bd
selection-background=242c56
urls=39c5cf

[colors-light]
alpha=0.88
alpha-mode=all
blur=yes

background=eff1f5
foreground=4c4f69

regular0=acb0be
regular1=d20f39
regular2=40a02b
regular3=df8e1d
regular4=1e66f5
regular5=ea76cb
regular6=179299
regular7=6c6f85

bright0=9ca0b0
bright1=d20f39
bright2=40a02b
bright3=df8e1d
bright4=1e66f5
bright5=ea76cb
bright6=179299
bright7=7c7f93

selection-foreground=4c4f69
selection-background=acb0be
urls=1e66f5
