# Retro Eighties (eighties.jpg)
# class                 border    background text      indicator child_border
client.focused          #ff4da6   #242c56    #bca9bd   #ff4da6   #ff4da6
client.focused_inactive #5d515d   #242c56    #da9e50   #5d515d   #5d515d
client.unfocused        #514249   #1f1b24    #8b75c2   #514249   #514249
client.urgent           #39c5cf   #242c56    #1f1b24   #39c5cf   #39c5cf
client.placeholder      #562f21   #1f1b24    #5d515d   #562f21   #562f21

default_border pixel 2
default_floating_border pixel 2
