# -*- conf -*-
# Knight Rider — KITT dashboard

[main]
initial-color-theme=dark

[colors-dark]
alpha=0.90
alpha-mode=all
blur=yes

background=08061c
foreground=f1c09f

regular0=5c112e
regular1=d71d33
regular2=e5612a
regular3=468aa2
regular4=f09d5a
regular5=4b454f
regular6=a3582f
regular7=f1c09f

bright0=4b454f
bright1=d71d33
bright2=f09d5a
bright3=468aa2
bright4=e5612a
bright5=9c1531
bright6=c6404d
bright7=ffffff

selection-foreground=f1c09f
selection-background=5c112e
urls=468aa2

[colors-light]
alpha=0.88
alpha-mode=all
blur=yes

background=eff1f5
foreground=4c4f69

regular0=acb0be
regular1=d20f39
regular2=40a02b
regular3=df8e1d
regular4=1e66f5
regular5=ea76cb
regular6=179299
regular7=6c6f85

bright0=9ca0b0
bright1=d20f39
bright2=40a02b
bright3=df8e1d
bright4=1e66f5
bright5=ea76cb
bright6=179299
bright7=7c7f93

selection-foreground=4c4f69
selection-background=acb0be
urls=1e66f5
