# Knight Rider — KITT dashboard (knightrider.png)
# class                 border    background text      indicator child_border
client.focused          #d71d33   #5c112e    #f1c09f   #d71d33   #d71d33
client.focused_inactive #a3582f   #5c112e    #f09d5a   #a3582f   #a3582f
client.unfocused        #4b454f   #08061c    #a3582f   #4b454f   #4b454f
client.urgent           #468aa2   #5c112e    #08061c   #468aa2   #468aa2
client.placeholder      #5c112e   #08061c    #4b454f   #5c112e   #5c112e

default_border pixel 2
default_floating_border pixel 2
