# Terminator / Skynet — matches wallhaven_w89pvq wallpaper
# class                 border    background text      indicator child_border
client.focused          #e60000   #141414    #e8eae5   #e60000   #e60000
client.focused_inactive #5c6060   #141414    #c7c4b5   #5c6060   #5c6060
client.unfocused        #3d3a41   #0c1317    #808983   #3d3a41   #3d3a41
client.urgent           #ff1a1a   #141414    #e8eae5   #ff1a1a   #ff1a1a
client.placeholder      #242424   #0c1317    #5c6060   #242424   #242424

default_border pixel 2
default_floating_border pixel 2
