# -*- conf -*-
# Biker Mice from Mars

[main]
initial-color-theme=dark

[colors-dark]
alpha=0.88
alpha-mode=all
blur=yes

background=111115
foreground=c7c7c7

regular0=2a3055
regular1=c41e24
regular2=39ff14
regular3=b79071
regular4=68748d
regular5=5e5c5f
regular6=aea296
regular7=c7c7c7

bright0=4e3c3e
bright1=c41e24
bright2=39ff14
bright3=b79071
bright4=2b3d8b
bright5=9e2a2f
bright6=68748d
bright7=ffffff

selection-foreground=c7c7c7
selection-background=2a3055
urls=c41e24

[colors-light]
alpha=0.88
alpha-mode=all
blur=yes

background=eff1f5
foreground=4c4f69

regular0=acb0be
regular1=d20f39
regular2=40a02b
regular3=df8e1d
regular4=1e66f5
regular5=ea76cb
regular6=179299
regular7=6c6f85

bright0=9ca0b0
bright1=d20f39
bright2=40a02b
bright3=df8e1d
bright4=1e66f5
bright5=ea76cb
bright6=179299
bright7=7c7f93

selection-foreground=4c4f69
selection-background=acb0be
urls=1e66f5
