# Biker Mice from Mars (bikermice.jpg)
# class                 border    background text      indicator child_border
client.focused          #c41e24   #2a3055    #c7c7c7   #c41e24   #c41e24
client.focused_inactive #68748d   #2a3055    #b79071   #68748d   #68748d
client.unfocused        #5e5c5f   #111115    #aea296   #5e5c5f   #5e5c5f
client.urgent           #39ff14   #2a3055    #111115   #39ff14   #39ff14
client.placeholder      #4e3c3e   #111115    #68748d   #4e3c3e   #4e3c3e

default_border pixel 2
default_floating_border pixel 2
