# -*- conf -*-
# Predator — Jungle

[main]
initial-color-theme=dark

[colors-dark]
alpha=0.88
alpha-mode=all
blur=yes

background=101a13
foreground=c6cba5

regular0=2e522e
regular1=d41f2b
regular2=6caf62
regular3=bcaa66
regular4=975e31
regular5=668197
regular6=4c6348
regular7=c6cba5

bright0=575533
bright1=d41f2b
bright2=6caf62
bright3=bcaa66
bright4=2c4454
bright5=a4593f
bright6=668197
bright7=ffffff

selection-foreground=c6cba5
selection-background=2e522e
urls=d41f2b

[colors-light]
alpha=0.88
alpha-mode=all
blur=yes

background=eff1f5
foreground=4c4f69

regular0=acb0be
regular1=d20f39
regular2=40a02b
regular3=df8e1d
regular4=1e66f5
regular5=ea76cb
regular6=179299
regular7=6c6f85

bright0=9ca0b0
bright1=d20f39
bright2=40a02b
bright3=df8e1d
bright4=1e66f5
bright5=ea76cb
bright6=179299
bright7=7c7f93

selection-foreground=4c4f69
selection-background=acb0be
urls=1e66f5
