# Predator — Jungle (predator.jpg)
# class                 border    background text      indicator child_border
client.focused          #d41f2b   #2e522e    #c6cba5   #d41f2b   #d41f2b
client.focused_inactive #4c6348   #2e522e    #bcaa66   #4c6348   #4c6348
client.unfocused        #575533   #101a13    #668197   #575533   #575533
client.urgent           #6caf62   #2e522e    #101a13   #6caf62   #6caf62
client.placeholder      #2e522e   #101a13    #4c6348   #2e522e   #2e522e

default_border pixel 2
default_floating_border pixel 2
