# Star Wars — Hoth light (tiefighter.jpg / X-wing)
# class                 border    background text      indicator child_border
client.focused          #a8282b   #d3dde7    #262b42   #a8282b   #a8282b
client.focused_inactive #73a4c8   #e8eef4    #515b72   #73a4c8   #73a4c8
client.unfocused        #aec8de   #f0f4f7    #64738c   #aec8de   #aec8de
client.urgent           #ff5a5f   #d3dde7    #262b42   #ff5a5f   #ff5a5f
client.placeholder      #c5d5e3   #f0f4f7    #91a0b3   #c5d5e3   #c5d5e3

default_border pixel 2
default_floating_border pixel 2
