# -*- conf -*-
# Back to the Future Part III

[main]
initial-color-theme=dark

[colors-dark]
alpha=0.88
alpha-mode=all
blur=yes

background=0b0a21
foreground=dae2d7

regular0=55403a
regular1=c41e3a
regular2=72adda
regular3=e4a764
regular4=e8d6a3
regular5=6e8ba6
regular6=c8a670
regular7=dae2d7

bright0=5a718c
bright1=c41e3a
bright2=72adda
bright3=e4a764
bright4=e8d6a3
bright5=964d3b
bright6=9bb6c1
bright7=ffffff

selection-foreground=dae2d7
selection-background=55403a
urls=c41e3a

[colors-light]
alpha=0.88
alpha-mode=all
blur=yes

background=eff1f5
foreground=4c4f69

regular0=acb0be
regular1=d20f39
regular2=40a02b
regular3=df8e1d
regular4=1e66f5
regular5=ea76cb
regular6=179299
regular7=6c6f85

bright0=9ca0b0
bright1=d20f39
bright2=40a02b
bright3=df8e1d
bright4=1e66f5
bright5=ea76cb
bright6=179299
bright7=7c7f93

selection-foreground=4c4f69
selection-background=acb0be
urls=1e66f5
