# Back to the Future Part III (backtothefuture.jpg)
# class                 border    background text      indicator child_border
client.focused          #c41e3a   #55403a    #dae2d7   #c41e3a   #c41e3a
client.focused_inactive #6e8ba6   #55403a    #e8d6a3   #6e8ba6   #6e8ba6
client.unfocused        #5a718c   #0b0a21    #9bb6c1   #5a718c   #5a718c
client.urgent           #e4a764   #55403a    #0b0a21   #e4a764   #e4a764
client.placeholder      #55403a   #0b0a21    #6e8ba6   #55403a   #55403a

default_border pixel 2
default_floating_border pixel 2
