# -*- conf -*-
# Teenage Mutant Ninja Turtles

[main]
initial-color-theme=dark

[colors-dark]
alpha=0.88
alpha-mode=all
blur=yes

background=191c28
foreground=b5bbcb

regular0=4c3642
regular1=ef4444
regular2=3b82f6
regular3=f59e0b
regular4=8b5cf6
regular5=505768
regular6=4e6e5d
regular7=b5bbcb

bright0=2d334a
bright1=ef4444
bright2=3b82f6
bright3=f59e0b
bright4=8b5cf6
bright5=95646b
bright6=64728b
bright7=ffffff

selection-foreground=b5bbcb
selection-background=2d334a
urls=8b5cf6

[colors-light]
alpha=0.88
alpha-mode=all
blur=yes

background=eff1f5
foreground=4c4f69

regular0=acb0be
regular1=d20f39
regular2=40a02b
regular3=df8e1d
regular4=1e66f5
regular5=ea76cb
regular6=179299
regular7=6c6f85

bright0=9ca0b0
bright1=d20f39
bright2=40a02b
bright3=df8e1d
bright4=1e66f5
bright5=ea76cb
bright6=179299
bright7=7c7f93

selection-foreground=4c4f69
selection-background=acb0be
urls=1e66f5
