# Teenage Mutant Ninja Turtles (turtles1.jpg)
# class                 border    background text      indicator child_border
client.focused          #8b5cf6   #2d334a    #b5bbcb   #8b5cf6   #8b5cf6
client.focused_inactive #64728b   #2d334a    #728aa7   #64728b   #64728b
client.unfocused        #4c3642   #191c28    #505768   #4c3642   #4c3642
client.urgent           #f59e0b   #2d334a    #191c28   #f59e0b   #f59e0b
client.placeholder      #374759   #191c28    #64728b   #374759   #374759

default_border pixel 2
default_floating_border pixel 2
