# -*- conf -*-
# Star Wars — Dark Side Campfire

[main]
initial-color-theme=dark

[colors-dark]
alpha=0.88
alpha-mode=all
blur=yes

background=2f0504
foreground=f6f596

regular0=5f2d1b
regular1=d44d1d
regular2=996533
regular3=cba663
regular4=f6f596
regular5=6e492b
regular6=7f8056
regular7=f6f596

bright0=3d2a18
bright1=ff8c00
bright2=cba663
bright3=f6f596
bright4=d44d1d
bright5=996533
bright6=6e492b
bright7=ffffff

selection-foreground=f6f596
selection-background=5f2d1b
urls=d44d1d

[colors-light]
alpha=0.88
alpha-mode=all
blur=yes

background=eff1f5
foreground=4c4f69

regular0=acb0be
regular1=d20f39
regular2=40a02b
regular3=df8e1d
regular4=1e66f5
regular5=ea76cb
regular6=179299
regular7=6c6f85

bright0=9ca0b0
bright1=d20f39
bright2=40a02b
bright3=df8e1d
bright4=1e66f5
bright5=ea76cb
bright6=179299
bright7=7c7f93

selection-foreground=4c4f69
selection-background=acb0be
urls=1e66f5
