# Star Wars — Dark Side Campfire (star_wars.jpg)
# class                 border    background text      indicator child_border
client.focused          #d44d1d   #5f2d1b    #f6f596   #d44d1d   #d44d1d
client.focused_inactive #6e492b   #5f2d1b    #cba663   #6e492b   #6e492b
client.unfocused        #3d2a18   #2f0504    #996533   #3d2a18   #3d2a18
client.urgent           #f6f596   #5f2d1b    #2f0504   #f6f596   #f6f596
client.placeholder      #5f2d1b   #2f0504    #6e492b   #5f2d1b   #5f2d1b

default_border pixel 2
default_floating_border pixel 2
